### ISSUE TITLE
Win support ;)

### ISSUE THREAD

**Issue by JohnRSim** [Yarrney/sapper-tailwind-firebase#1]
Please add windows support :)

I've temporarily added the following - 

```
"build": "npm run build:tailwind && sapper build --legacy && Xcopy /E /Y \"__sapper__/build\" \"functions/__sapper__/build\"",
"prebuild": "del /q \"functions/__sapper__/build\"",
"build:tailwind": "set NODE_ENV=production postcss static/tailwind.css -o static/index.css"
```

**Comment by Yarrney** [comment]
@JohnRSim you'll have to forgive me, I'm still finalising some config for themes that I'd like to add in and I'll come back around to it!

**Comment by JohnRSim** [comment]
keep up the great work I've started playing with this as the base of my new project.

**Comment by JohnRSim** [comment]
Thanks I will give it a go this week and pull in the updates.

**Comment by Yarrney** [comment]
My friend @brewsoftware suggested adding "cross-env" to resolve this - so you shouldn't have to do any extra config to get started. Let me know!
